name: safe_my_code
description: "A lightweight package of helpers and extensions for writing safer, cleaner, and more robust Dart & Flutter code."
version: 0.0.1
homepage: "https://github.com/karimegaber/safe_my_code.git"
repository: "https://github.com/karimegaber/safe_my_code.git"

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
